/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assessments */
        get: operations["list_assessments_api_v1_assessments_get"];
        put?: never;
        /**
         * Submit Assessment
         * @description Submit an assessment task; returns task_id immediately for polling.
         */
        post: operations["submit_assessment_api_v1_assessments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment Result */
        get: operations["get_assessment_result_api_v1_assessments__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{task_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Activity */
        get: operations["get_task_activity_api_v1_assessments__task_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{task_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Comment */
        post: operations["add_comment_api_v1_assessments__task_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{task_id}/remediations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tracked Remediations */
        get: operations["list_tracked_remediations_api_v1_assessments__task_id__remediations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{task_id}/remediations/{remediation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Remediation Tracking */
        post: operations["update_remediation_tracking_api_v1_assessments__task_id__remediations__remediation_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{task_id}/reuse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reuse Candidates */
        get: operations["get_reuse_candidates_api_v1_assessments__task_id__reuse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{task_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Assessment */
        post: operations["review_assessment_api_v1_assessments__task_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/agents/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Integration Status */
        get: operations["get_agent_integration_status_api_v1_integrations_agents_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kb/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Upload a document to the knowledge base (vector + graph RAG).
         */
        post: operations["upload_document_api_v1_kb_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kb/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Kb
         * @description Hybrid RAG query: vector similarity + graph retrieval.
         */
        post: operations["query_kb_api_v1_kb_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kb/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex Kb */
        post: operations["reindex_kb_api_v1_kb_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Skills
         * @description List all available skills (built-in + custom).
         */
        get: operations["list_skills_api_v1_skills__get"];
        put?: never;
        /**
         * Create Skill
         * @description Create a new custom skill.
         */
        post: operations["create_skill_api_v1_skills__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Skill
         * @description Get a specific skill definition.
         */
        get: operations["get_skill_api_v1_skills__skill_id__get"];
        /**
         * Update Skill
         * @description Update an existing custom skill.
         */
        put: operations["update_skill_api_v1_skills__skill_id__put"];
        post?: never;
        /**
         * Delete Skill
         * @description Delete a custom skill.
         */
        delete: operations["delete_skill_api_v1_skills__skill_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config Llm
         * @description Current LLM config with secrets masked.
         */
        get: operations["config_llm_config_llm_get"];
        /**
         * Update Llm Config
         * @description Update runtime LLM config for the current FastAPI process.
         */
        put: operations["update_llm_config_config_llm_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentIntegrationStatus */
        AgentIntegrationStatus: {
            /** A2A Skills */
            a2a_skills?: string[];
            /**
             * Access Mode
             * @enum {string}
             */
            access_mode: "loopback_only" | "bearer_token" | "disabled";
            /**
             * Data Boundary
             * @default Agent protocols do not return raw documents. Configured LLM data policy still applies.
             */
            data_boundary: string;
            /**
             * Document Roots Configured
             * @default 0
             */
            document_roots_configured: number;
            /** Enabled */
            enabled: boolean;
            /** Mcp Tools */
            mcp_tools?: string[];
            /** Protocols */
            protocols?: components["schemas"]["AgentProtocolEndpoint"][];
        };
        /** AgentProtocolEndpoint */
        AgentProtocolEndpoint: {
            /** Enabled */
            enabled: boolean;
            /** Endpoint */
            endpoint: string;
            /**
             * Protocol
             * @enum {string}
             */
            protocol: "mcp" | "a2a";
            /** Transport */
            transport: string;
        };
        /** AssessmentReport */
        AssessmentReport: {
            /** Compliance Gaps */
            compliance_gaps?: components["schemas"]["ComplianceGap"][];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Cross Phase Refs */
            cross_phase_refs?: components["schemas"]["CrossPhaseRef"][];
            /**
             * Format
             * @default json
             * @enum {string}
             */
            format: "json" | "markdown";
            metadata?: components["schemas"]["ReportMetadata"] | null;
            /** Phase */
            phase?: string | null;
            /** Remediations */
            remediations?: components["schemas"]["Remediation"][];
            /** Risk Items */
            risk_items?: components["schemas"]["RiskItem"][];
            /** Sources */
            sources?: components["schemas"]["SourceCitation"][];
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "partial" | "failed";
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string;
            threat_model?: components["schemas"]["ThreatModel"] | null;
            /**
             * Version
             * @default 2.0
             */
            version: string;
            /** Vulnerabilities */
            vulnerabilities?: components["schemas"]["Vulnerability"][];
        };
        /** AssessmentTaskCreated */
        AssessmentTaskCreated: {
            /** Message */
            message?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "queued";
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
        };
        /** AssessmentTaskResult */
        AssessmentTaskResult: {
            /** Assignee */
            assignee?: string | null;
            /** Comments */
            comments?: {
                [key: string]: unknown;
            }[];
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Message */
            error_message?: string | null;
            report?: components["schemas"]["AssessmentReport"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "review_pending" | "approved" | "rejected" | "escalated" | "completed" | "failed";
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** Body_submit_assessment_api_v1_assessments_post */
        Body_submit_assessment_api_v1_assessments_post: {
            /**
             * Collaborative Mode
             * @default true
             */
            collaborative_mode: boolean;
            /**
             * Files
             * @description Documents to assess
             */
            files: string[];
            /**
             * Phase
             * @default auto
             * @enum {string}
             */
            phase: "auto" | "requirements" | "design" | "development" | "testing" | "deployment" | "operations" | "full_ssdlc";
            /** Project Id */
            project_id?: string | null;
            /** Scenario Id */
            scenario_id?: string | null;
            /** Skill Id */
            skill_id?: string | null;
        };
        /** Body_upload_document_api_v1_kb_documents_post */
        Body_upload_document_api_v1_kb_documents_post: {
            /** File */
            file: string;
        };
        /** CommentRequest */
        CommentRequest: {
            /** Content */
            content: string;
            /**
             * User Id
             * @default anonymous
             */
            user_id: string;
        };
        /** ComplianceGap */
        ComplianceGap: {
            /** Citation Ids */
            citation_ids?: string[];
            /** Confidence */
            confidence?: number | null;
            /** Control Or Clause */
            control_or_clause: string;
            /** Evidence Suggestion */
            evidence_suggestion?: string | null;
            /** Framework */
            framework?: string | null;
            /** Gap Description */
            gap_description: string;
            /** Id */
            id: string;
            /** Phase */
            phase?: string | null;
        };
        /** CrossPhaseRef */
        CrossPhaseRef: {
            /** Relationship */
            relationship: string;
            /** Source Id */
            source_id: string;
            /** Source Phase */
            source_phase: string;
            /** Target Id */
            target_id: string;
            /** Target Phase */
            target_phase: string;
        };
        /** DreadScore */
        DreadScore: {
            /** Affected Users */
            affected_users?: number | null;
            /** Damage */
            damage?: number | null;
            /** Discoverability */
            discoverability?: number | null;
            /** Exploitability */
            exploitability?: number | null;
            /** Reproducibility */
            reproducibility?: number | null;
            /** Total */
            total?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KBQueryRequest */
        KBQueryRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** KBReindexRequest */
        KBReindexRequest: {
            /** Directory */
            directory: string;
        };
        /** LLMConfigUpdate */
        LLMConfigUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Provider
             * @description LLM provider id
             */
            provider: string;
        };
        /** Remediation */
        Remediation: {
            /** Action */
            action: string;
            /** External Ticket */
            external_ticket?: string | null;
            /** Id */
            id: string;
            /** Phase */
            phase?: string | null;
            /** Priority */
            priority?: ("low" | "medium" | "high" | "critical") | null;
            /** Related Gap Ids */
            related_gap_ids?: string[];
            /** Related Risk Ids */
            related_risk_ids?: string[];
            /** Related Threat Ids */
            related_threat_ids?: string[];
            /** Related Vuln Ids */
            related_vuln_ids?: string[];
        };
        /** RemediationTracking */
        RemediationTracking: {
            /** Due At */
            due_at?: string | null;
            /** Evidence Refs */
            evidence_refs?: string[];
            /** External Ticket */
            external_ticket?: string | null;
            /** Notes */
            notes?: string | null;
            /** Owner */
            owner?: string | null;
            /** Remediation Id */
            remediation_id: string;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "in_progress" | "resolved" | "verified" | "closed";
            /** Updated At */
            updated_at?: string | null;
        };
        /** RemediationTrackingUpdateRequest */
        RemediationTrackingUpdateRequest: {
            /** Due At */
            due_at?: string | null;
            /** Evidence Refs */
            evidence_refs?: string[] | null;
            /** External Ticket */
            external_ticket?: string | null;
            /** Notes */
            notes?: string | null;
            /** Owner */
            owner?: string | null;
            /** Status */
            status?: ("open" | "in_progress" | "resolved" | "verified" | "closed") | null;
        };
        /** ReportMetadata */
        ReportMetadata: {
            /** Completed At */
            completed_at?: string | null;
            /** Model Used */
            model_used?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** Scenario Id */
            scenario_id?: string | null;
            /** Skill Id */
            skill_id?: string | null;
            /** Ssdlc Phase */
            ssdlc_phase?: string | null;
            /** Ssdlc Stage */
            ssdlc_stage?: string | null;
        };
        /** ReviewActionRequest */
        ReviewActionRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "reject" | "comment" | "escalate";
            /** Assignee */
            assignee?: string | null;
            /** Comment */
            comment?: string | null;
        };
        /** RiskItem */
        RiskItem: {
            /** Category */
            category?: string | null;
            /** Citation Ids */
            citation_ids?: string[];
            /** Confidence */
            confidence?: number | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Phase */
            phase?: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high" | "critical";
            /** Source Ref */
            source_ref?: string | null;
            /** Title */
            title: string;
        };
        /** Skill */
        Skill: {
            /**
             * Compliance Frameworks
             * @description Frameworks to reference (e.g. 'ISO 27001')
             */
            compliance_frameworks?: string[];
            /**
             * Description
             * @description Short description of the role
             */
            description: string;
            /**
             * Id
             * @description Unique identifier (e.g. 'iso-auditor')
             */
            id: string;
            /**
             * Is Builtin
             * @description Whether this is a system preset
             * @default false
             */
            is_builtin: boolean;
            /**
             * Name
             * @description Display name (e.g. 'ISO 27001 Lead Auditor')
             */
            name: string;
            /**
             * Risk Focus
             * @description Key areas to focus on (e.g. 'Access Control')
             */
            risk_focus?: string[];
            /**
             * System Prompt
             * @description Base system prompt defining the persona and constraints
             */
            system_prompt: string;
        };
        /** SkillCreate */
        SkillCreate: {
            /**
             * Compliance Frameworks
             * @default []
             */
            compliance_frameworks: string[];
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Risk Focus
             * @default []
             */
            risk_focus: string[];
            /** System Prompt */
            system_prompt: string;
        };
        /** SkillUpdate */
        SkillUpdate: {
            /** Compliance Frameworks */
            compliance_frameworks?: string[] | null;
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** Risk Focus */
            risk_focus?: string[] | null;
            /** System Prompt */
            system_prompt?: string | null;
        };
        /** SourceCitation */
        SourceCitation: {
            /** Evidence Link */
            evidence_link?: string | null;
            /** Excerpt */
            excerpt: string;
            /** File */
            file: string;
            /** Id */
            id: string;
            /** Page */
            page?: number | null;
            /** Paragraph Id */
            paragraph_id?: string | null;
            /** Score */
            score?: number | null;
        };
        /** Threat */
        Threat: {
            /** Affected Component */
            affected_component?: string | null;
            /**
             * Category
             * @enum {string}
             */
            category: "Spoofing" | "Tampering" | "Repudiation" | "InformationDisclosure" | "DenialOfService" | "ElevationOfPrivilege";
            /** Description */
            description: string;
            dread_score?: components["schemas"]["DreadScore"] | null;
            /** Id */
            id: string;
            /** Mitigations */
            mitigations?: string[];
        };
        /** ThreatModel */
        ThreatModel: {
            /** Methodology */
            methodology?: ("STRIDE" | "DREAD" | "STRIDE_DREAD") | null;
            /** Threats */
            threats?: components["schemas"]["Threat"][];
        };
        /** TrackedRemediation */
        TrackedRemediation: {
            remediation: components["schemas"]["Remediation"];
            tracking: components["schemas"]["RemediationTracking"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vulnerability */
        Vulnerability: {
            /** Cvss Score */
            cvss_score?: number | null;
            /** Cwe Id */
            cwe_id?: string | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Linked Threat Id */
            linked_threat_id?: string | null;
            /** Location */
            location?: string | null;
            /** Remediation */
            remediation?: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "low" | "medium" | "high" | "critical";
            /** Source Tool */
            source_tool?: string | null;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "in_progress" | "fixed" | "accepted" | "false_positive";
            /** Title */
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_assessments_api_v1_assessments_get: {
        parameters: {
            query?: {
                status?: string | null;
                assignee?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentTaskResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_assessment_api_v1_assessments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_assessment_api_v1_assessments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentTaskCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_result_api_v1_assessments__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentTaskResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_activity_api_v1_assessments__task_id__activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_comment_api_v1_assessments__task_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tracked_remediations_api_v1_assessments__task_id__remediations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedRemediation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_remediation_tracking_api_v1_assessments__task_id__remediations__remediation_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                remediation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemediationTrackingUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemediationTracking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reuse_candidates_api_v1_assessments__task_id__reuse_get: {
        parameters: {
            query?: {
                top_k?: number;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_assessment_api_v1_assessments__task_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_integration_status_api_v1_integrations_agents_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentIntegrationStatus"];
                };
            };
        };
    };
    upload_document_api_v1_kb_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_kb_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_kb_api_v1_kb_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KBQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_kb_api_v1_kb_reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KBReindexRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_api_v1_skills__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"][];
                };
            };
        };
    };
    create_skill_api_v1_skills__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_api_v1_skills__skill_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_skill_api_v1_skills__skill_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_skill_api_v1_skills__skill_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_llm_config_llm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_llm_config_config_llm_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
