"""governance schema

Revision ID: ebcc5bce6929
Revises:
Create Date: 2026-06-30 23:17:37.012911
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "ebcc5bce6929"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auditlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resource", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auditlog_action"), "auditlog", ["action"], unique=False)
    op.create_index(
        op.f("ix_auditlog_resource"), "auditlog", ["resource"], unique=False
    )
    op.create_index(op.f("ix_auditlog_user_id"), "auditlog", ["user_id"], unique=False)
    op.create_table(
        "user",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "governance_audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "action", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "resource_type", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column(
            "resource_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "ip_address", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_governance_audit_logs_action"),
        "governance_audit_logs",
        ["action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_governance_audit_logs_created_at"),
        "governance_audit_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_governance_audit_logs_resource_id"),
        "governance_audit_logs",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_governance_audit_logs_user_id"),
        "governance_audit_logs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "org_framework_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("framework_ids", sa.JSON(), nullable=False),
        sa.Column(
            "default_review_mode",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column("require_human_for_high_risk_ai", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "policy_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "language", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False
        ),
        sa.Column(
            "doc_type", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False
        ),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("uploaded_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "kb_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "business_owner",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column(
            "risk_tier", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column(
            "control_profile",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=True,
        ),
        sa.Column("compliance_frameworks", sa.JSON(), nullable=False),
        sa.Column(
            "review_mode", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column("framework_ids_locked", sa.Boolean(), nullable=False),
        sa.Column("involves_ai_ml", sa.Boolean(), nullable=True),
        sa.Column(
            "ai_risk_class", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column("slsa_target_level", sa.Integer(), nullable=True),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "system_type", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column(
            "hosting_type", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column(
            "data_classification",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
        sa.Column("risk_level", sa.Integer(), nullable=True),
        sa.Column(
            "organization", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(
        op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "compliance_obligations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "framework_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "framework_version",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column("applicability_rationale", sa.Text(), nullable=True),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_compliance_obligations_framework_id"),
        "compliance_obligations",
        ["framework_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_obligations_project_id"),
        "compliance_obligations",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "control_instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "control_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "framework_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("framework_citation", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("normalized_requirement", sa.Text(), nullable=False),
        sa.Column("expected_evidence", sa.JSON(), nullable=False),
        sa.Column("review_focus", sa.JSON(), nullable=False),
        sa.Column("is_applicable", sa.Boolean(), nullable=False),
        sa.Column("applicability_rationale", sa.Text(), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column(
            "review_mode", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "ai_score", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column("ai_rationale", sa.Text(), nullable=True),
        sa.Column("ai_missing_evidence", sa.JSON(), nullable=True),
        sa.Column("ai_confidence", sa.Float(), nullable=True),
        sa.Column("ai_requires_human", sa.Boolean(), nullable=True),
        sa.Column("ai_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "human_decision", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column("human_notes", sa.Text(), nullable=True),
        sa.Column("human_reviewer_id", sa.Integer(), nullable=True),
        sa.Column("human_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["human_reviewer_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_instances_control_id"),
        "control_instances",
        ["control_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_instances_framework_id"),
        "control_instances",
        ["framework_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_instances_project_id"),
        "control_instances",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_instances_status"),
        "control_instances",
        ["status"],
        unique=False,
    )
    op.create_table(
        "gate_submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("gate_number", sa.Integer(), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column("intake_payload", sa.JSON(), nullable=True),
        sa.Column("reviewer_comments", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gate_submissions_gate_number"),
        "gate_submissions",
        ["gate_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gate_submissions_project_id"),
        "gate_submissions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gate_submissions_status"), "gate_submissions", ["status"], unique=False
    )
    op.create_table(
        "policy_embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column(
            "language", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["policy_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_embeddings_document_id"),
        "policy_embeddings",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "prompt_audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sub_agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column(
            "mvp_task", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column(
            "prompt_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "response_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("token_count_in", sa.Integer(), nullable=False),
        sa.Column("token_count_out", sa.Integer(), nullable=False),
        sa.Column("pii_fields_redacted", sa.JSON(), nullable=True),
        sa.Column("safety", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prompt_audit_logs_created_at"),
        "prompt_audit_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_audit_logs_message_id"),
        "prompt_audit_logs",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_audit_logs_mvp_task"),
        "prompt_audit_logs",
        ["mvp_task"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_audit_logs_project_id"),
        "prompt_audit_logs",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_audit_logs_sub_agent_run_id"),
        "prompt_audit_logs",
        ["sub_agent_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_audit_logs_user_id"),
        "prompt_audit_logs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "questionnaire_instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("generated_from_frameworks", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questionnaire_instances_project_id"),
        "questionnaire_instances",
        ["project_id"],
        unique=True,
    )
    op.create_table(
        "sub_agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("gate", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column(
            "sub_agent_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("run_output", sa.JSON(), nullable=True),
        sa.Column("last_transitioned_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sub_agent_runs_project_id"),
        "sub_agent_runs",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_agent_runs_status"), "sub_agent_runs", ["status"], unique=False
    )
    op.create_table(
        "control_evidence_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("control_instance_id", sa.Uuid(), nullable=False),
        sa.Column(
            "evidence_type", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("ai_analysis", sa.JSON(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_instance_id"],
            ["control_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_evidence_items_control_instance_id"),
        "control_evidence_items",
        ["control_instance_id"],
        unique=False,
    )
    op.create_table(
        "question_instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("questionnaire_id", sa.Uuid(), nullable=False),
        sa.Column(
            "question_key", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("question_label", sa.Text(), nullable=False),
        sa.Column(
            "question_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("group", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("ask_when", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("maps_to_control_ids", sa.JSON(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("answered_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["questionnaire_id"],
            ["questionnaire_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_instances_questionnaire_id"),
        "question_instances",
        ["questionnaire_id"],
        unique=False,
    )
    op.create_table(
        "requirement_rows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("gate_submission_id", sa.Uuid(), nullable=False),
        sa.Column(
            "requirement_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
        sa.Column(
            "domain", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("requirement_text", sa.Text(), nullable=False),
        sa.Column("organization_guidance", sa.Text(), nullable=True),
        sa.Column(
            "applicability", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column(
            "risk_level", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column(
            "review_status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("ai_confidence", sa.Float(), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("review_history", sa.JSON(), nullable=False),
        sa.Column("scd_extras", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gate_submission_id"],
            ["gate_submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requirement_rows_gate_submission_id"),
        "requirement_rows",
        ["gate_submission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirement_rows_review_status"),
        "requirement_rows",
        ["review_status"],
        unique=False,
    )
    op.create_table(
        "evidence_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requirement_row_id", sa.Uuid(), nullable=False),
        sa.Column(
            "evidence_type", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.Column("ai_analysis", sa.JSON(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requirement_row_id"],
            ["requirement_rows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_items_requirement_row_id"),
        "evidence_items",
        ["requirement_row_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_evidence_items_requirement_row_id"), table_name="evidence_items"
    )
    op.drop_table("evidence_items")
    op.drop_index(
        op.f("ix_requirement_rows_review_status"), table_name="requirement_rows"
    )
    op.drop_index(
        op.f("ix_requirement_rows_gate_submission_id"), table_name="requirement_rows"
    )
    op.drop_table("requirement_rows")
    op.drop_index(
        op.f("ix_question_instances_questionnaire_id"), table_name="question_instances"
    )
    op.drop_table("question_instances")
    op.drop_index(
        op.f("ix_control_evidence_items_control_instance_id"),
        table_name="control_evidence_items",
    )
    op.drop_table("control_evidence_items")
    op.drop_index(op.f("ix_sub_agent_runs_status"), table_name="sub_agent_runs")
    op.drop_index(op.f("ix_sub_agent_runs_project_id"), table_name="sub_agent_runs")
    op.drop_table("sub_agent_runs")
    op.drop_index(
        op.f("ix_questionnaire_instances_project_id"),
        table_name="questionnaire_instances",
    )
    op.drop_table("questionnaire_instances")
    op.drop_index(op.f("ix_prompt_audit_logs_user_id"), table_name="prompt_audit_logs")
    op.drop_index(
        op.f("ix_prompt_audit_logs_sub_agent_run_id"), table_name="prompt_audit_logs"
    )
    op.drop_index(
        op.f("ix_prompt_audit_logs_project_id"), table_name="prompt_audit_logs"
    )
    op.drop_index(op.f("ix_prompt_audit_logs_mvp_task"), table_name="prompt_audit_logs")
    op.drop_index(
        op.f("ix_prompt_audit_logs_message_id"), table_name="prompt_audit_logs"
    )
    op.drop_index(
        op.f("ix_prompt_audit_logs_created_at"), table_name="prompt_audit_logs"
    )
    op.drop_table("prompt_audit_logs")
    op.drop_index(
        op.f("ix_policy_embeddings_document_id"), table_name="policy_embeddings"
    )
    op.drop_table("policy_embeddings")
    op.drop_index(op.f("ix_gate_submissions_status"), table_name="gate_submissions")
    op.drop_index(op.f("ix_gate_submissions_project_id"), table_name="gate_submissions")
    op.drop_index(
        op.f("ix_gate_submissions_gate_number"), table_name="gate_submissions"
    )
    op.drop_table("gate_submissions")
    op.drop_index(op.f("ix_control_instances_status"), table_name="control_instances")
    op.drop_index(
        op.f("ix_control_instances_project_id"), table_name="control_instances"
    )
    op.drop_index(
        op.f("ix_control_instances_framework_id"), table_name="control_instances"
    )
    op.drop_index(
        op.f("ix_control_instances_control_id"), table_name="control_instances"
    )
    op.drop_table("control_instances")
    op.drop_index(
        op.f("ix_compliance_obligations_project_id"),
        table_name="compliance_obligations",
    )
    op.drop_index(
        op.f("ix_compliance_obligations_framework_id"),
        table_name="compliance_obligations",
    )
    op.drop_table("compliance_obligations")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("policy_documents")
    op.drop_table("org_framework_configs")
    op.drop_index(
        op.f("ix_governance_audit_logs_user_id"), table_name="governance_audit_logs"
    )
    op.drop_index(
        op.f("ix_governance_audit_logs_resource_id"), table_name="governance_audit_logs"
    )
    op.drop_index(
        op.f("ix_governance_audit_logs_created_at"), table_name="governance_audit_logs"
    )
    op.drop_index(
        op.f("ix_governance_audit_logs_action"), table_name="governance_audit_logs"
    )
    op.drop_table("governance_audit_logs")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_auditlog_user_id"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_resource"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_action"), table_name="auditlog")
    op.drop_table("auditlog")
    # ### end Alembic commands ###
